### ISSUE TITLE
bvdPluginManager is not defined

### ISSUE THREAD

**Issue by GeorgiKarapetrov** [MicroFocus/ColorYourData#15]
Where can I find the bvdPluginManager module/library/class/function or whatever it is called in js?

The output of `node vega_channel.js`
> <...>\ColorYourData\widgets\examples\vega_charts\vega_channel.js:9
> bvdPluginManager.registerWidget({
> ^
> 
> ReferenceError: bvdPluginManager is not defined
>     at Object.<anonymous> (C:\Users\GKarapetrov\ColorYourData\widgets\examples\vega_charts> \vega_channel.js:9:1)
> [90m    at Module._compile (internal/modules/cjs/loader.js:959:30)[39m
> [90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)[39m
> [90m    at Module.load (internal/modules/cjs/loader.js:815:32)[39m
> [90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)[39m
> [90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)[39m
> [90m    at internal/main/run_main_module.js:17:11[39m

Bear with me, please. I am new to Node and BVD but I am to develop BVDs for a client. I can no longer find a standalone copy of BVD, (it is deprecated), and I don't have the computing resourse to run OBM. So I cannot find out how BVD provides the bvdPluginManager. A google search gives me nothing. Please, help.

**Comment by hulmgulm-at-work** [comment]
Hello Georgi,
this file vega_channel.js is an example widget. You need to copy it onto your BVD server, upload a dashboard which will use this widget and then it will be loaded by your browser to display that widget.
It's nothing you can run standalone with node.

**Comment by GeorgiKarapetrov** [comment]
I was afraid so, thank you.

**Comment by GeorgiKarapetrov** [comment]
This client in particular has a classic installation of BVD. (I don't know which version of BVD it is, but it is stand alone and so it must be 10.63 or prior.) Does the classic BVD have the bvdPluginManager API? (I see a first mention of it with the 10.64 documentation.)

**Comment by hulmgulm-at-work** [comment]
I'm sorry, but this API is only available in containerized BVD versions.
