### ISSUE TITLE
dynamic_image.js - a issue of property 

### ISSUE THREAD

**Issue by lesteryin** [MicroFocus/ColorYourData#3]
![image](https://user-images.githubusercontent.com/14816598/38159478-b0fe386e-34db-11e8-8fb7-cec21f27cd02.png)

I modify the line 51, the issue can be fixed
from
      image.attr('xlink:href', interpolate(ctx.getProperty('image_url'), envelope.data));

to 
      image.attr('xlink:href', interpolate(ctx.getProperty('bvd_image_url'), envelope.data)

**Comment by klausb** [comment]
Fixed.
